### PR TITLE
Added EPG and russian language support

### PR DESCRIPTION
**Pull request by Silhouette2022**

### CODE REVIEW

**Comment by Publish3r** [comment]
Nice new feature, the EPG. I added the new language strings for germany. I can setup EPG source. But it don't work for me. Can't open playlist now.
My Kodi Debug Log: https://pastebin.ubuntu.com/p/xdKyZXT3fd/

**Comment by Silhouette2022** [comment]
make sure your epg list in xml format. Some of them are *.xml.gz and it's not supported.
As well it can be useful if you can send me a link to your epg source.

**Comment by Publish3r** [comment]
Ok, tested with xml format now.

1st test:
Playlist: https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv_main.m3u
EPG: https://ricxepg.nl/epg_data/rytecDE_Basic.gz (Extracted and uploaded to my Homeserver).
Addon can open playlist, but i can't see the EPG anywhere.

2nd test:
My own playlist from Homeserver and my own EPG as xml from Homeserver (EPG generated by https://github.com/sunsettrack4/easyepg)
Addon opens an empty folder.

3rd test:
Playlist: https://i.mjh.nz/PlutoTV/de.m3u8
EPG: https://i.mjh.nz/PlutoTV/de.xml
Working!

**Comment by Silhouette2022** [comment]
> 
> 
> Is it possible to write private messages with you @Silhouette2022 ?

Sure

**Comment by Silhouette2022** [comment]
> 
> 
> Ok, tested with xml format now.
> 
> 1st test:
> Playlist: https://raw.githubusercontent.com/jnk22/kodinerds-iptv/master/iptv/kodi/kodi_tv_main.m3u
> EPG: https://ricxepg.nl/epg_data/rytecDE_Basic.gz (Extracted and uploaded to my Homeserver).
> Addon can open playlist, but i can't see the EPG anywhere.
> 
> 2nd test:
> My own playlist from Homeserver and my own EPG as xml from Homeserver (EPG generated by https://github.com/sunsettrack4/easyepg)
> Addon opens an empty folder.
> 
> 3rd test:
> Playlist: https://i.mjh.nz/PlutoTV/de.m3u8
> EPG: https://i.mjh.nz/PlutoTV/de.xml
> Working!

Those are expected results for test 1 and test 3.
I have nothing to say about test 2. If you really need it you can send/post generated file

**Comment by Publish3r** [comment]
I need the https://i.mjh.nz/ lists only. And they are working.
And that one: https://telerising.de/epg/easyepg-basic.gz
It's very minimal. Tryed as extracted xml on my homeserver. Not working.
A m3u file example: https://pastebin.ubuntu.com/p/Y4gYdWCrFm/

**Pull request merged**
